name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Cordova
      run: npm install -g cordova
    - name: Create Android Project
      run: |
        cordova create myapp com.omar.signlink "Omar SignLink"
        cp index.html myapp/www/
        cd myapp
        cordova platform add android
        # أمر برميجي ذكي لحقن إذن الكاميرا رسمياً داخل نظام الأندرويد تلقائياً
        sed -i '/<\/widget>/i <platform name="android"><config-file parent="\/*" target="AndroidManifest.xml"><uses-permission android:name="android.permission.CAMERA" \/><\/config-file><\/platform>' config.xml
        sed -i 's/version="1.0.0"/version="3.0.0"/' config.xml
        cordova build android --no-telemetry
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Official-App-APK
        path: myapp/platforms/android/app/build/outputs/apk/debug/*.apk
