name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # خطوة أساسية لإعداد أدوات الأندرويد في السيرفر
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Android Project
        run: |
          cordova create myapp com.omar.signlink "Omar SignLink"
          cp index.html myapp/www/
          cd myapp
          cordova platform add android
          cordova plugin add cordova-plugin-android-permissions --save
          cordova plugin add cordova-plugin-camera --save
          
          # السطر السحري لحقن إذن الكاميرا قسرياً داخل ملف الأندرويد الرئيسي
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.CAMERA" \/>' platforms/android/app/src/main/AndroidManifest.xml
          
          cordova build android --no-telemetry

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Official-App-APK
          path: myapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
